<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../include/head.jsp" %>

<html>
<head>
    <meta charset="UTF-8">
    <title>Demo菜单</title>
    <%@ include file="../include/innerHead.jsp" %>
</head>
<body>

<!-- 主要内容 -->
<script type="text/javascript">
    var demoData = [
    {text:"WEB控件",isOpen:true,children:[
        {text:"表单类控件",children:[
            {text:"文本输入栏",href:"textfield.jsp"},
            {text:"多行文本输入栏",href:"textarea.jsp"},
            {text:"日期输入栏",href:"datefield.jsp"},
            {text:"复/单选框",href:"checkRadio.jsp"},
            {text:"复/单选框组",href:"checkRadioGroup.jsp"},
            {text:"下拉选择框",href:"select.jsp"},
            {text:"<font color='gray'>复合选择框(弃用)</font>",href:"combobox.jsp"},
            {text:"多选框",href:"multiselect.jsp"},
            {text:"联动下拉框",href:"interactselect.jsp"},
            {text:"Label",href:"label.jsp"},
            {text:"时间Label",href:"timelabel.jsp"},
            {text: "高级输入框", isOpen: true, children: [
                {text:"自动填充栏",href:"autocomplete.jsp"},
                {text:"文本编辑器",href:"doceditor.jsp"}
            ]},
            {text:"高级选择器",isOpen:true,children:[
                {text:"双向选择器",href:"doubleSelect.jsp"},
                {text:"可删除选择器",href:"removableselect.jsp"},
                {text:"分类选择器",href:"classifiedselect.jsp"},
                {text:"字母选择器",href:"letterselect.jsp"},
                {text:"星级选择器",href:"starselect.jsp"},
                {text:"颜色选择器",href:"colorSelect.jsp"},
                {text:"滑动条",href:"slider.jsp"}
            ]},
            {text:"表单",isOpen:true,children:[
                {text:"普通",href:"form.jsp"},
                {text:"异步初始化",href:"form_init.jsp"},
                {text:"文件上传",href:"fileUpload.jsp"}
            ]}
        ]},
        {text:"操作类控件",children:[
            {text:"按钮",href:"button.jsp"},
            {text:"菜单按钮",href:"buttonMenu.jsp"},
            {text:"链接",href:"a.jsp"}
//            {text:"<font color='gray'>菜单(NAN)</font>",href:"#"},
//            {text:"<font color='gray'>右键菜单(NAN)</font>",href:"#"}
        ]},
        {text:"数据类控件",children:[
            {text:"表格",isOpen:true,children:[
                {text:"普通",href:"table.jsp"},
                {text:"分组",href:"table_group.jsp"},
                {text:"<font color='gray'>固定高度(弃用)</font>",href:"table_height.jsp"},
                {text:"事件",href:"table_event.jsp"},
                {text:"表达式",href:"table_expr.jsp"},
                {text:"List",href:"table_list.jsp"},
                {text:"自定义分页List",href:"table_listCust.jsp"},
                {text:"汇总",href:"table_collect.jsp"},
                {text:"复选框应用",href:"table_checkbox.jsp"},
                {text:"导出",href:"table_export.jsp"},
                {text:"详细",href:"table_detail.jsp"},
                {text:"行号",href:"table_rowNum.jsp"},
                {text:"帮助信息",href:"table_help.jsp"},
                {text:"列合并",href:"table_mergeCol.jsp"}
            ]},
            {text:"固定列表格",isOpen:true,children:[
                {text:"普通",href:"tablefix.jsp"},
                {text:"固定高度",href:"tablefix_height.jsp"}
            ]},
            {text:"树",isOpen:true,children:[
                {text:"静态",href:"tree.jsp"},
                {text:"动态",href:"tree_dynamic.jsp"}
            ]}
        ]},
        {text:"布局类控件",children:[
            {text:"对话框",href:"dialog.jsp"},
            {text:"<font color='gray'>间距(弃用)</font>",href:"spacing.jsp"},
            {text:"<font color='gray'>布局盒(弃用)</font>",href:"box.jsp"},
            {text:"FieldSet",href:"fieldset.jsp"},
            {text:"面板",href:"panel.jsp"},
            {text:"标签面板",href:"tab.jsp"},
            {text:"窗口",href:"window.jsp"},
            {text:"工具栏",href:"toolbar.jsp"}
        ]},
        {text:"图表类控件",children:[
            {text:"线状图表",isOpen:true,children:[
                {text:"普通",href:"chart_line.jsp"},
                {text:"圆滑",href:"chart_spline.jsp"},
                {text:"显示值",href:"chart_line_datalabels.jsp"},
                {text:"反转",href:"chart_line_inverted.jsp"},
                {text:"自定义图标",href:"chart_line_icon.jsp"},
                {text:"对齐线",href:"chart_line_duiqi.jsp"}
            ]},
            {text:"面积图表",isOpen:true,children:[
                {text:"普通",href:"chart_area.jsp"},
                {text:"圆滑",href:"chart_areaspline.jsp"},
                {text:"百分比",href:"chart_area_percent.jsp"},
                {text:"堆栈",href:"chart_area_stacked.jsp"}
            ]},
            {text:"横木图表",isOpen:true,children:[
                {text:"普通",href:"chart_bar.jsp"},
                {text:"堆栈",href:"chart_bar_stacked.jsp"}
            ]},
            {text:"柱状图表",isOpen:true,children:[
                {text:"普通",href:"chart_column.jsp"},
                {text:"堆栈",href:"chart_column_stacked.jsp"},
                {text:"标签旋转",href:"chart_column_rotation.jsp"},
                {text:"事件",href:"chart_column_event.jsp"}
            ]},
            {text:"饼状图表",isOpen:true,children:[
                {text:"普通",href:"chart_pie.jsp"},
                {text:"面包圈",href:"chart_pie_donut.jsp"}

            ]},
            {text:"散布图表",isOpen:true,children:[
                {text:"普通",href:"chart_scatter.jsp"}
            ]},
            {text:"组合图表",isOpen:true,children:[
                {text:"范例1",href:"chart_combo.jsp"},
                {text:"范例2",href:"chart_combo2.jsp"}
            ]},
            {text:"股票图表",isOpen:true,children:[
                {text:"普通",href:"chart_stock.jsp"},
                {text:"多个数据",href:"chart_stock_towLines.jsp"},
                {text:"标记",href:"chart_stock_flag.jsp"}
            ]}
        ]},
        {text:"控件API",children:[
            {text:"表格相关",children:[
                {text:"stk_adjust",href:"stk_adjust.jsp"},
                {text:"stk_call",href:"stk_call.jsp"},
                {text:"stk_checkedData",href:"stk_checkedData.jsp"},
                {text:"stk_checkedHtmlData",href:"stk_checkedHtmlData.jsp"},
                {text:"stk_collectData",href:"stk_collectData.jsp"},
                {text:"stk_hasSelect",href:"stk_hasSelect.jsp"},
                {text:"stk_detail",href:"stk_detail.jsp"},
                {text:"stk_info",href:"stk_info.jsp"},
                {text:"stk_init",href:"stk_init.jsp"},
                {text:"stk_jump",href:"stk_jump.jsp"},
                {text:"stk_query",href:"stk_query.jsp"},
                {text:"stk_selectData",href:"stk_selectData.jsp"},
                {text:"stk_selectHtmlData",href:"stk_selectHtmlData.jsp"}
            ]},
            {text:"外框Tab相关",children:[
                {text:"stk_go",href:"stk_go.jsp"},
                {text:"stk_getTab",href:"stk_getTab.jsp"},
                {text:"stk_getParentTab",href:"stk_getParentTab.jsp"},
                {text:"stk_navigate",href:"stk_navigate.jsp"},
                {text:"stk_removeSelf",href:"stk_removeSelf.jsp"},
                {text:"stk_removeTab",href:"stk_removeTab.jsp"},
                {text:"stk_refreshHomeModule",href:"stk_refreshHomeModule.jsp"}
            ]},
            {text:"Form相关",children:[
                {text:"stk_reset",href:"stk_reset.jsp"},
                {text:"stk_submit",href:"stk_submit.jsp"},
                {text:"stk_check",href:"stk_check.jsp"},
                {text:"stk_checkForm",href:"stk_checkForm.jsp"}
            ]},
            {text:"选择器相关",children:[
                {text:"stk_addOptions",href:"stk_addOptions.jsp"},
                {text:"stk_emptyOptions",href:"stk_emptyOptions.jsp"},
                {text:"stk_firstOption",href:"stk_firstOption.jsp"},
                {text:"stk_removeItem",href:"stk_removeItem.jsp"},
                {text:"stk_removeOptions",href:"stk_removeOptions.jsp"},
                {text:"stk_resetOptions",href:"stk_resetOptions.jsp"}
            ]},
            {text:"stk_checked",href:"stk_checked.jsp"},
//            {text:"stk_close",href:"stk_close.jsp"},
            {text:"stk_closeMask",href:"stk_closeMask.jsp"},
            {text:"stk_closeQtip",href:"stk_closeQtip.jsp"},
            {text:"stk_disabled",href:"stk_disabled.jsp"},
            {text:"stk_flushCache",href:"stk_flushCache.jsp"},
            {text:"stk_hide",href:"stk_hide.jsp"},
            {text:"stk_hideCol",href:"stk_hideCol.jsp"},
            {text:"stk_init",href:"stk_init.jsp"},
            {text:"stk_map",href:"stk_map.jsp"},
            {text:"stk_qtip",href:"stk_qtip.jsp"},
            {text:"stk_readOnly",href:"stk_readOnly.jsp"},
            {text:"stk_refresh",href:"stk_refresh.jsp"},
            {text:"stk_renderRow",href:"stk_renderRow.jsp"},
            {text:"stk_show",href:"stk_show.jsp"},
            {text:"stk_showCol",href:"stk_showCol.jsp"},
            {text:"stk_showMask",href:"stk_showMask.jsp"},
            {text:"stk_showMenu",href:"stk_showMenu.jsp"},
            {text:"stk_text",href:"stk_text.jsp"},
            {text:"stk_title",href:"stk_title.jsp"},
            {text:"stk_toggleChecked",href:"stk_toggleChecked.jsp"},
            {text:"stk_val",href:"stk_val.jsp"},
            {text:"ajax调用",href:"ajax_call.jsp"},
            {text:"控件渲染",href:"renderTo.jsp"}
        ]},
        {text:"范例应用",children:[
            {text:"增删查改",href:"curd_ajax.jsp"}
        ]},
        {text:"静态模板<font color='red'>(1)</font>",children:[
            {text:"登录",href:"moban_denglu.jsp"},
            {text:"外部报告详细页",href:"moban_baogao.jsp"},
            {text:"表格样式二",href:"moban_table2.jsp"},
            {text:"电话沟通",href:"moban_dianhua.jsp"},
            {text:"电话沟通-新",href:"moban_dianhua2.jsp"},
            {text:"按钮",href:"moban_button.jsp"},
            {text:"高级查询",href:"moban_search.jsp"},
            {text:"查询表单",href:"moban_form_chaxun.jsp"},
            {text:"输入表单-简单",href:"moban_form_jiandan.jsp"},
            {text:"输入表单-复杂",href:"moban_form_fuza.jsp"},
            {text:"查看表单-弹窗",href:"moban_form_tanchuang.jsp"},
            {text:"查看表单-跳转",href:"moban_form_tiaozhuan.jsp"},
            {text:"报告数量统计",href:"moban_tongji.jsp"},
            {text:"多人协作-日期",href:"moban_xiezuo_riqi.jsp"},
            {text:"多人协作-分类",href:"moban_xiezuo_fenlei.jsp"},
            {text:"内部报告-评论",href:"moban_neibu_pinglun.jsp"},
            {text:"内部报告-详细",href:"moban_neibu_xiangxi.jsp"},
            {text:"投资池",href:"moban_touzichi.jsp"},
            {text:"权限管理",href:"moban_quanxian.jsp"},
            {text:"全文检索",href:"moban_jiansuo.jsp"},
            {text:"个股全景图",href:"moban_stock.jsp"},
            {text:"固定列表格",href:"moban_tablefix.jsp"},
            {text:"公告",href:"moban_baogao2.jsp"},
            {text:"个人中心",href:"moban_home.jsp"},
            {text:"手动批量调整",href:"moban_shoudongS1.jsp"},
            {text:"支持中心",href:"moban_zhichi.jsp"},
            {text:"语言中心",href:"moban_yuyan.jsp"},
            {text:"日程模式",href:"moban_richeng.jsp"},
            {text:"工作流明细",href:"moban_wf_mingxi.jsp"},
            {text:"管理人全景图",href:"moban_guanliren.jsp"},
            {text:"基金经理全景图",href:"moban_jijinjingli.jsp"},
            {text:"基金全景图",href:"moban_jijin.jsp"},
            {text:"报告审批",href:"moban_baogao_shenpi.jsp"},
            {text:"报告编辑",href:"moban_baogao_bianji.jsp"},
            {text:"竖标签",href:"moban_shuTab.jsp"},
            {text:"周日程",href:"moban_zhouricheng.jsp"},
            {text:"项目执行",href:"moban_xiangmu.jsp"},
            {text:"高级搜索输入<font color='red'> new!</font>",href:"moban_inputMenu.jsp"}
        ]},
        {text:"Welcome",href:"welcome.jsp"}
    ]}
    ];
    </script>

    <ui:tree jsList="demoData"  hrefTarget="mainFrame" width="300px"/>
</body>
</html>