<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<table class='stk_demo_table'>
    <tr>
        <td colspan="3" align="center" style="font-size:large;font-weight:bolder;">分类、字母选择器参数</td>
    </tr>
    <tr>
        <td width="15%"><p align="center"><strong>参数名</strong><strong> </strong></p></td>
        <td width="15%"><p align="center"><strong>默认值</strong><strong> </strong></p></td>
        <td><p align="center"><strong>说明</strong><strong> </strong></p></td>
    </tr>
    <tr>
        <td>clazz</td>
        <td>&nbsp;</td>
        <td>action名</td>
    </tr>
    <tr>
        <td>jsParam</td>
        <td>&nbsp;</td>
        <td>js参数Map</td>
    </tr>
    <tr>
        <td>multiple</td>
        <td>false</td>
        <td>是否多选，默认false</td>
    </tr>
    <tr>
        <td>interactFunction</td>
        <td>&nbsp;</td>
        <td>确定后调用的函数</td>
    </tr>
    <tr>
        <td>width</td>
        <td>380px</td>
        <td>宽度</td>
    </tr>
    <tr>
        <td>cellWidth</td>
        <td>100px</td>
        <td>内部元素宽度</td>
    </tr>
    <tr>
        <td>defaultValue</td>
        <td>&nbsp;</td>
        <td>初始时文本，多选时初始化用</td>
    </tr>
    <tr>
        <td>height</td>
        <td>&nbsp;</td>
        <td>高度</td>
    </tr>
    <tr>
        <td>target</td>
        <td>&nbsp;</td>
        <td>目标空间id，显示的时候在哪个控件的位置</td>
    </tr>
    <tr>
        <td>direction</td>
        <td>bottom</td>
        <td>显示在target的位置方向，还可选top</td>
    </tr>
    <tr>
        <td>allowSelectClass</td>
        <td>false</td>
        <td>允许选择分类，仅适用于分类选择器</td>
    </tr>
    <tr>
        <td>positionX</td>
        <td>false</td>
        <td>相对弹出位置的水平调整，比如-10px</td>
    </tr>
    <tr>
        <td>positionY</td>
        <td>false</td>
        <td>相对弹出位置的垂直调整，比如-10px</td>
    </tr>
    <tr>
        <td>selectAll</td>
        <td>false</td>
        <td>是否支持全选</td>
    </tr>
</table>