<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<table class='stk_demo_table'>
    <tr>
        <td colspan="3" align="center" style="font-size:large;font-weight:bolder;">Table参数</td>
    </tr>
    <tr>
        <td width="15%"><p align="center"><strong>参数名</strong><strong> </strong></p></td>
        <td width="15%"><p align="center"><strong>默认值</strong><strong> </strong></p></td>
        <td><p align="center"><strong>说明</strong><strong> </strong></p></td>
    </tr>
    <tr>
        <td>pageSize</td>
        <td>&nbsp;</td>
        <td>每页显示多少条记录</td>
    </tr>
    <tr>
        <td>actionClass</td>
        <td>&nbsp;</td>
        <td>表格控件对应的类：比如com.sinitek.xxxx</td>
    </tr>
    <tr>
        <td>queryForm</td>
        <td>&nbsp;</td>
        <td>如果有查询表单，填写form的id</td>
    </tr>
    <tr>
        <td>width</td>
        <td>100%</td>
        <td>显示宽度</td>
    </tr>
    <tr>
        <td>height</td>
        <td>&nbsp;</td>
        <td>高度，设置后固定表格高度超出显示滚动条</td>
    </tr>
    <tr>
        <td>rowHeight</td>
        <td>25px</td>
        <td>数据行高</td>
    </tr>
    <tr>
        <td>tableWidth</td>
        <td>100%</td>
        <td>实际宽度 (当实际宽度>显示宽度时，下方出现滚动条)</td>
    </tr>
    <tr>
        <td>allowInit</td>
        <td>true</td>
        <td>允许页面打开时初始化数据</td>
    </tr>
    <tr>
        <td>*personal</td>
        <td>&nbsp;</td>
        <td>个性化配置名称</td>
    </tr>
    <tr>
        <td>allowDetail</td>
        <td>false</td>
        <td>允许每行数据查看明细</td>
    </tr>
    <tr>
        <td>*allowColumnOrd</td>
        <td>true</td>
        <td>允许配置列顺序</td>
    </tr>
    <tr>
        <td>allowExport</td>
        <td>false</td>
        <td>允许导出excel文件</td>
    </tr>
    <tr>
        <td>exportOption</td>
        <td>all,select</td>
        <td>导出选项：all,select 表示全部和勾选都有</td>
    </tr>
    <tr>
        <td>title</td>
        <td>&nbsp;</td>
        <td>标题</td>
    </tr>
    <tr>
        <td>sortType</td>
        <td>normal</td>
        <td>normal,none,comb，表示普通排序，不排序，组合排序</td>
    </tr>
    <tr>
        <td>pageInfoType</td>
        <td>normal</td>
        <td>normal,simple：表示普通分页信息，简单分页信息</td>
    </tr>
    <tr>
        <td>nowrap</td>
        <td>false</td>
        <td>列是否不换行</td>
    </tr>
    <tr>
        <td>mode</td>
        <td>fixed</td>
        <td>表格模式，可选fixed,auto</td>
    </tr>
    <tr>
        <td>allowBlankRow</td>
        <td>false</td>
        <td>是否允许空行填充总记录数</td>
    </tr>
    <tr>
        <td>allowHead</td>
        <td>true</td>
        <td>是否显示表格头</td>
    </tr>
    <tr>
        <td>allowConfigPageSize</td>
        <td>true</td>
        <td>是否pageSize由用户保存</td>
    </tr>
    <tr>
        <td>allowDuplicate</td>
        <td>true</td>
        <td>允许分页数据重复(很少情况下才需要设置false)</td>
    </tr>
    <tr>
        <td>exportFileName</td>
        <td>&nbsp;</td>
        <td>自定义导出文件名</td>
    </tr>
    <tr>
        <td>blankText</td>
        <td>&nbsp;</td>
        <td>数据为空时显示的文本，默认" "</td>
    </tr>
    <tr>
        <td>subList</td>
        <td>false</td>
        <td>List模式是否会自动subList,默认true</td>
    </tr>
    <tr>
        <td>extraOrderBy</td>
        <td>false</td>
        <td>加在orderby后面的必有排序，为了解决某些问题</td>
    </tr>
    <tr>
        <td>exportMaxRow</td>
        <td>&nbsp;</td>
        <td>导出最大行数</td>
    </tr>
    <tr>
        <td>faster</td>
        <td>false</td>
        <td>牺牲部分功能，提高性能</td>
    </tr>
</table>